version: "3"

services:
  heimdall:
    container_name: heimdall
    image: linuxserver/heimdall:latest
    ports:
      - "8080:80/tcp"
      - "8443:443/tcp"
    volumes:
      - "$HOME/docker-data/heimdall:/config"
    restart:
      unless-stopped
