version: "3"

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    ports:
      - "8000:8000/tcp"
      - "9443:9443/tcp"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$HOME/docker-data/portainer_data:/data"
    restart: always
